### ISSUE TITLE
find a good login and implement

### ISSUE THREAD

**Issue by mnmeyers** [Travelist-itp/staging#12]
@dmalkin @AaronGoldstein @hillarytzeng

**Comment by mnmeyers** [comment]
maybe find one? but probably just create our own

**Comment by dmalkin** [comment]
Let's create our own after I talk with Bo about our database. I've been emailing him most of the day

**Comment by mnmeyers** [comment]
I actually found an example in my code from my other class of a login. rudimentary, but it's fine
