### ISSUE TITLE
link to our own local jquery, not USC's

### ISSUE THREAD

**Issue by mnmeyers** [Travelist-itp/staging#26]
https://github.com/Travelist-itp/staging/blob/master/Travelist/settings.php#L4

**Comment by dmalkin** [comment]
what is our local jquery src name?

**Comment by mnmeyers** [comment]
<script src="assets/js/jquery.min.js"></script>

**Comment by mnmeyers** [comment]
```
<script src="assets/js/jquery.min.js"></script>
```

**Comment by dmalkin** [comment]
duh hahah my brain is so fried right now

**Comment by mnmeyers** [comment]
I actually don't know why it doesn't work without that since it's included in the footer. I guess it hast to be before
