### ISSUE TITLE
Edit the wiki, write about using the GitHub client with screenshots

### ISSUE THREAD

**Issue by mnmeyers** [Travelist-itp/staging#4]
Here is the wiki: https://github.com/Travelist-itp/staging/wiki/Common-Command-Line-Commands-for-Mac

To take a screenshot and put pictures in, do shift + command + control + 4 and then command + v them in the comments here, and then use the link to that picture as the src in the wiki. (you can't directly put in pictures in the wiki, so it's a workaround.)

Much appreciated.

**Comment by mnmeyers** [comment]
![image](https://cloud.githubusercontent.com/assets/10369508/6279712/11ec974e-b85a-11e4-82c8-4780aa071b68.png)

**Comment by dmalkin** [comment]
![image](https://cloud.githubusercontent.com/assets/10947444/6279968/e48d080e-b85b-11e4-9dd4-48d8de5bc1e4.png)

**Comment by dmalkin** [comment]
![image](https://cloud.githubusercontent.com/assets/10947444/6279977/00a4e818-b85c-11e4-9718-2703ec564d68.png)

**Comment by dmalkin** [comment]
![image](https://cloud.githubusercontent.com/assets/10947444/6280041/d7474b0e-b85c-11e4-8e05-684ee6a80414.png)

**Comment by dmalkin** [comment]
![image](https://cloud.githubusercontent.com/assets/10947444/6280122/8fd46472-b85d-11e4-9816-8776dec91137.png)

**Comment by dmalkin** [comment]
![image](https://cloud.githubusercontent.com/assets/10947444/6280137/c84ca95e-b85d-11e4-95ba-15ef192113e8.png)

**Comment by dmalkin** [comment]
![image](https://cloud.githubusercontent.com/assets/10947444/6280198/445aefec-b85e-11e4-87b1-235bcffbfb4c.png)

**Comment by mnmeyers** [comment]
![image](https://cloud.githubusercontent.com/assets/10369508/6279716/15d18ba8-b85a-11e4-9cb1-90ecbfeaa8ae.png)
