### ISSUE TITLE
fix the php on explore page

### ISSUE THREAD

**Issue by mnmeyers** [Travelist-itp/staging#49]
@AaronGoldstein if there's anything you wanna say about it, what you are tyring to do, comment here

**Comment by AaronGoldstein** [comment]
I can't get the php working because I can not connect the database to my page. When I include the auth page I get errors. The javascript and php to display the database should be correct and should work once the database is connected.

**Comment by mnmeyers** [comment]
I'm confused by your code. You can't require connect.php because header.php requires it. You're already connected to the database because of the header. Your code doesn't work even without that line though, there are a couple of possible issues. 1. get_locations.php does not exist in our repository, maybe you forgot to push it? 2. I'm not entirely sure what get_coords.php does or that it properly connects to the database. Also, config.php does not exist in our repository, so that will cause a fatal error. Do you wanna discuss over messaging tonight?

**Comment by mnmeyers** [comment]
https://github.com/Travelist-itp/staging/commit/f1894826c46ae36230a56c816c1596d14ffbe120

**Comment by AaronGoldstein** [comment]
lets do it tommorow

**Comment by mnmeyers** [comment]
duplicate
