### ISSUE TITLE
Tasks for this week

### ISSUE THREAD

**Issue by mnmeyers** [Travelist-itp/staging#5]
Hey all, our "feature build" is due on Wednesday and so is our QA stuff. I'm requesting that you finish the html/css of your page by <strong>Tuesday night</strong> so that we could finish QA by Wednesday night. Some guidelines for your pages:
<ul>
    <li>Please name your files simply and lowercase. E.g., explore, profile, friends, etc. No "travelist-itp-explore-page"</li>
    <li>Please put your page in the first folder on github, ("Travelist"-> <a href="https://github.com/Travelist-itp/staging/tree/master/Travelist">here</a>) do not create your own directories.</li>
    <li>Please save your pages as .php. I will put the php connection code that we need to include inside my header so don't worry about that on your page.
    </li>
    <li>You will need to include my header and footer. You should not have any html tags, body tags, scripts etc because those are included in my header and footer files. (but you should have a link to your own css if you created a customized stylesheet in addition to bootstrap's. Include any custom scripts for your page at the bottom) At the top of your page write (with the opening php tag)<strong> require('header.php');?></strong> and then at the bottom of the page: <strong> require('footer.php');?></strong> </li>
<ul><li>Note: it's better if you start building your pages with these requires first (and not plopped in at the end) so that if you have conflicts with the styles from the header and footer, you can sort them out first.</li></ul>
    <li>Please make your pages responsive, i.e. use % instead of fixed pixel widths whenever possible.</li>
<li>Please use Bootstrap styles and grid system as much as possible before resorting to creating your own styles.</li>
<br>Also, I found the proper google API that we need to use. It should cover all our needs and no money required. It's called the <a href="https://developers.google.com/places/documentation/index">Google Places API</a>. I'm going to do more research on that, feel free to help me out. Just curious, who is officially the backend lead? (Use @ before a person's name to tag them in a comment.)
 
</ul>

**Comment by mnmeyers** [comment]
@dmalkin @AaronGoldstein @drewashen @hillarytzeng

**Comment by dmalkin** [comment]
@mnmeyers @hillarytzeng  my file is temporary until I get Hillary's code to lay it over. Basically, mine will be hidden until the profile settings button is pressed. I will make sure to delete my file once I've completed integrating it. It is static right now as well.

**Comment by mnmeyers** [comment]
@dmalkin everyone's is going to be pretty much static at the moment, the only php we will have for now is the connection to the server and including my header and footer files.

**Comment by mnmeyers** [comment]
@dmalkin please follow the above guidelines for prof-settings.html (make it php, do the requires, don't include the skeleton, etc)

**Comment by dmalkin** [comment]
@mnmeyers done! Got the PHP up. not perfectly displayed, but will fix that when I have Hillary's page
